apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rag-d1744864769393-gitops
  description: This is GitOps manifest for rag-d1744864769393   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=rag-d1744864769393
    janus-idp.io/tekton: rag-d1744864769393 
    backstage.io/kubernetes-id: rag-d1744864769393 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:rag-d1744864769393  
